---
- name: Deploy Java Web App
  hosts: localhost
  become: yes

  tasks:

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Copy WAR file
      copy:
        src: ../target/java-webapp.war
        dest: /opt/java-webapp.war

    - name: Run application
      shell: nohup java -jar /opt/java-webapp.war &
